name: Sample Workflow

on:
  workflow_dispatch:
    inputs:
      string_input:
        description: 'A simple string input'
        required: true
        default: 'default string'
      boolean_input:
        description: 'A boolean input'
        required: true
        default: false
      choice_input:
        description: 'A choice input'
        required: true
        default: 'option1'
        options:
          - option1
          - option2
          - option3
      number_input:
        description: 'A number input'
        required: true
        default: 42
      environment_input:
        description: 'An environment input'
        required: true
        default: 'production'
        options:
          - development
          - staging
          - production
      date_input:
        description: 'A date input'
        required: true
        default: '2024-01-01'
      time_input:
        description: 'A time input'
        required: true
        default: '12:00'
      datetime_input:
        description: 'A datetime input'
        required: true
        default: '2024-01-01T12:00:00Z'
      file_input:
        description: 'A file input'
        required: true
      secret_input:
        description: 'A secret input'
        required: true

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print inputs
        run: |
          echo "String Input: ${{ github.event.inputs.string_input }}"
          echo "Boolean Input: ${{ github.event.inputs.boolean_input }}"
          echo "Choice Input: ${{ github.event.inputs.choice_input }}"
          echo "Number Input: ${{ github.event.inputs.number_input }}"
          echo "Environment Input: ${{ github.event.inputs.environment_input }}"
          echo "Date Input: ${{ github.event.inputs.date_input }}"
          echo "Time Input: ${{ github.event.inputs.time_input }}"
          echo "Datetime Input: ${{ github.event.inputs.datetime_input }}"
          echo "File Input: ${{ github.event.inputs.file_input }}"
          echo "Secret Input: ${{ github.event.inputs.secret_input }}"
